core52/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name='index'),
    path('productoPorCategoria/<int:id>', views.productosPorCategoria,name='productoPorCategoria'),
    path('productoPorNombre', views.buscar,name='productoPorNombre'),
    path('producto/<int:id>', views.detalle,name='producto'),
    path('carrito', views.carrito, name='carrito'),
    path('add_cart/<int:id>', views.add_cart, name='add_cart'),
    path('eliminarProductoCarrito/<int:producto_id>', views.eliminar_producto_carrito, name='eliminarProductoCarrito'),
    path('limpiarCarrito', views.limpiar_carrito, name='limpiarCarrito'),
    path('aumentarCantidad/<int:producto_id>', views.aumentar_cantidad, name='aumentarCantidad'),
    path('disminuirCantidad/<int:producto_id>', views.disminuir_cantidad, name='disminuirCantidad'),
]

web/templates/carrito copy.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Carrito</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Carrito</li>
    </ul>
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
        <article class="prod-li sectls">
            <div class="prod-li-inner">
                <a href="product.html" class="prod-li-img">
                    <img src="{{ value.imagen }}" alt="">
                </a>
                <div class="prod-li-cont">
                    <div class="prod-li-ttl-wrap">
                        <p>
                            <a href="#">{{value.categoria}}</a>
                        </p>
                        <h3><a href="product.html">{{ value.nombre }}</a></h3>
                    </div><!--
    No Space
    --><div class="prod-li-prices">
                    <div class="prod-li-price-wrap">
                        <p>Precio</p>
                        <p class="prod-li-price">${{value.precio}}</p>
                    </div>
                    <div class="prod-li-qnt-wrap">
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" value="{{value.cantidad}}">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                    </div>
                    <div class="prod-li-total-wrap">
                        <p>Total</p>
                        <p class="prod-li-total">${{value.subtotal}}</p>
                    </div>
                </div><!--
No Space
--></div>
                <div class="prod-li-info">
                    <div class="prod-li-rating-wrap">
                        <p data-rating="5" class="prod-li-rating">
                            <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                        </p>
                        <p class="prod-li-rating-count">12</p>
                    </div>
                    <p class="prod-li-add">
                        <a href="{% url 'web:eliminarProductoCarrito' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>Eliminar</span></a>
                    </p>
                    <p class="prod-li-information">
                        <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                    </p>
                </div>
            </div>
            <div class="page-styling prod-li-informations">

                <dl class="prod-li-props">
                    <dt>Marca:</dt>
                    <dd><a href="#">{{value.marca}}</a></dd>
                    <dt>Peso:</dt>
                    <dd>{{value.peso}} kg</dd>
                    <dt>Dimensiones:</dt>
                    <dd>{{value.dimension}}</dd>
                    <dt>Сolor:</dt>
                    <dd>{{value.color}}</dd>
                </dl>
            </div>
        </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:limpiarCarrito' %}" class="checkout-button button">Limpiar Carrito</a>
            <a href="{% url 'web:registrarPedido' %}" class="checkout-button button">Realizar Pedido</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
            </div>
        </div>
    </div>


</div>

{% endblock %}

web/templates/cuenta.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="maincont-ttl">Bienvenido - {{ user.first_name }} {{ user.last_name }}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Mi Cuenta</li>
    </ul>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <form method="post" action="{% url 'web:actualizarCliente' %}" class="register">
                        {% csrf_token %}
                        {{ frmCliente|crispy }}
                        <p class="auth-submit">
                            <input type="submit" value="Actualizar Datos">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

web/templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Checkout OK</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>COMPRA</li>
    </ul>
    <h2>GRACIAS POR TU COMPRA</h2>    
{% endblock %}

web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
        <div class="section-top">

            <h1 class="maincont-ttl">Catalogo</h1>
            <ul class="b-crumbs">
                <li><a href="{% url 'web:index' %}">Inicio</a></li>
                <li>Catalogo</li>
            </ul>
        </div>
        <!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
        <div class="section-wrap-withsb">
            <aside class="blog-sb-widgets section-sb" id="section-sb">
                <div class="theiaStickySidebar">
                    <p class="section-filter-toggle filter_hidden">
                        <a href="#" id="section-filter-toggle-btn">Filtros</a>
                    </p>
                    <div class="section-filter">
                        <div class="section-filter">
                            {% include 'includes/catalogo/categorias.html' %}
                        </div>
                    </div>
                </div>
            </aside>        <div class="section-list-withsb" id="section-list-withsb">
            <div class="theiaStickySidebar">
                {% include 'includes/catalogo/catalogo.html' %}
            </div><!-- .theiaStickySidebar -->
        </div><!-- .section-list-withsb -->
        </div><!-- .section-wrap-withsb -->
{% endblock %}

web/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tienda</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.formstyler.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mThumbnailScroller.css' %}">
    <link rel="stylesheet" href="{% static 'css/chosen.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">    <link rel="stylesheet" href="{% static 'css/elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements-media.css' %}">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">

</head>
<body>
<div id="page" class="site">

    {% include 'includes/navbar.html' %}

    {% include 'includes/header.html' %}

    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="cont maincont">
                    {% block content %}
                    {% endblock %}
                </div>
            </main><!-- #main -->
        </div><!-- #primary -->

    </div><!-- #content -->    {% include 'includes/footer.html' %}
</div><!-- #page -->

<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.4.1.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- SweetAlert2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!-- Alpine.js components -->
<!-- <script defer src="{% static 'js/alpine-components.js' %}"></script> -->
<!-- Alpine.js - Carga de componentes primero, luego Alpine -->
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>

</body>
</html>

web/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Registration / Login</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Registration & Login</li>
    </ul>                                                <article class="page-cont">
    <div class="page-styling">


        <div class="auth-wrap">
            <div class="auth-col">
                <h2>Login</h2>
                <form method="post" class="login" action="{% url 'web:loginUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="username">E-mail <span class="required">*</span></label>
                        <input type="text" id="username" name="usuario">
                    </p>
                    <p>
                        <label for="password">Password <span class="required">*</span></label>
                        <input type="password" id="password" name="password">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Login">
                        <input type="checkbox" id="rememberme" value="forever">
                        <label for="rememberme">Remember me</label>
                    </p>
                    <p>
                        <label for="alert-danger"> {{error}}</label>
                    </p>
                    <p class="auth-lost_password">
                        <a href="#">Lost your password?</a>
                    </p>
                </form>
            </div>
            <div class="auth-col">
                <h2>Registro</h2>
                <form method="post" class="register" action="{% url 'web:crearUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="reg_email">Email <span class="required">*</span></label>
                        <input type="email" id="reg_email" name="nuevoUsuario">
                    </p>
                    <p>
                        <label for="reg_password">Password <span class="required">*</span></label>
                        <input type="password" id="reg_password" name="nuevoPassword">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Crear Cuenta">
                    </p>
                </form>
            </div>
        </div>


    </div>
</article>

{% endblock %}

web/templates/pedido.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="maincont-ttl">PEDIDO NRO : {{pedido.nro_pedido}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Pedido</li>
    </ul>
<div class="page-styling">
    <div class="woocommerce prod-litems section-list">
            <h2>Fecha : {{pedido.fecha_registro}}</h2>
            {% for detalle in pedido.pedidodetalle_set.all %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="{{ detalle.producto.imagen.url }}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{detalle.producto.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{ detalle.producto.nombre }}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">${{detalle.producto.precio}}</p>
                            </div>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{detalle.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{detalle.subtotal}}</p>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
    </div>
    <div class="cart-actions">
            <div class="cart-collaterals">
                {{ formpaypal.render }}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">${{pedido.monto_total}}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

web/templates/plantilla.html
{% extends 'layout.html' %}
{% block content %}
{% endblock %}

web/templates/producto.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li><a href="/">Catalogo</a></li>
        <li>Producto</li>
    </ul>
    <article>
    <div class="prod">
        <div class="prod-slider-wrap prod-slider-shown">
            <div class="flexslider prod-slider" id="prod-slider">
                <ul class="slides">
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="#">
                            {% if producto.imagen %}
                            <img src="{{ producto.imagen.url }}" alt="">
                            {% else %}
                                <img src="{% static 'img/250x250.svg' %}" alt="Producto sin imagen">
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="#">
                            {% if producto.imagen %}
                                <img src="{{ producto.imagen.url }}" alt="">
                            {% else %}
                                <img src="{% static 'img/250x250.svg' %}" alt="Producto sin imagen">
                            {% endif %}
                        </a>
                    </li>
                </ul>
                <div class="prod-slider-count"><p>
                    <span class="count-cur">1</span> / <span class="count-all">2</span></p><p class="hover-label prod-slider-zoom">
                    <i class="icon ion-search"></i><span>Zoom In</span></p></div>
            </div>
            <div class="flexslider prod-thumbs" id="prod-thumbs">
                <ul class="slides">
                    <li>
                        <img src="{% static 'img/250x250.svg' %}" alt="Producto sin imagen">
                    </li>
                    <li>
                        <img src="{% static 'img/250x250.svg' %}" alt="Producto sin imagen">
                    </li>
                </ul>
            </div>
        </div>

        <div class="prod-cont">
            <div class="prod-rating-wrap">
                <p data-rating="4" class="prod-rating">
                    <i class="rating-ico" title="1"></i>
                    <i class="rating-ico" title="2"></i>
                    <i class="rating-ico" title="3"></i>
                    <i class="rating-ico" title="4"></i>
                    <i class="rating-ico" title="5"></i>
                </p>
                <p class="prod-rating-count">7</p>
            </div>
            <p class="prod-categs"><a href="#">Polos</a></p>
            <h1>{{ producto.nombre }}</h1>            <div class="variations_form cart" x-data="productoDetalle('{{ producto.id }}', '{{ producto.nombre }}')">
                <p class="prod-price">Q {{ producto.precio }}</p>
                <p class="prod-excerpt">{{ producto.descripcion }} 
                    <a id="prod-showdesc" class="prod-excerpt-more" href="#">read more</a></p>
                <div class="prod-add">
                    <form @submit.prevent="agregarAlCarrito">
                        {% csrf_token %}
                        <div class="variations">
                            <div class="variations-row">
                                <div class="label"><label>Color</label></div>
                                <div class="value">
                                    <select name="color" x-model="color">
                                        <option value="">Selecciona una opción</option>
                                        <option value="blue">Azul</option>
                                        <option value="green">Verde</option>
                                        <option value="yellow">Amarillo</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="button"><i class="icon ion-android-cart"></i> Agregar al Carrito</button>
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus" @click.prevent="incrementar"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" name="cantidad" x-model="cantidad" id="quantity-input">
                            <a href="#" class="qnt-minus prod-li-minus" @click.prevent="decrementar"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                    </form>
                </div>
            </div>
            <div class="prod-props">
                <dl class="product_meta">
                    
                    
                </dl>
            </div>
        </div>
    </div>    
<script>
    function productoDetalle(id, nombre) {
        return {
            id: id,
            nombre: nombre,
            cantidad: 1,
            color: '',
            
            incrementar() {
                this.cantidad = parseInt(this.cantidad) + 1 || 1;
            },
            
            decrementar() {
                this.cantidad = Math.max(1, parseInt(this.cantidad) - 1 || 1);
            },
            
            agregarAlCarrito() {
                // if (!this.color) {
                //     Swal.fire({
                //         title: 'Selecciona un color',
                //         text: 'Por favor selecciona un color antes de agregar al carrito',
                //         icon: 'warning',
                //         confirmButtonColor: '#3085d6'
                //     });
                //     return;
                // }
                  Swal.fire({
                    title: 'Añadir al carrito',
                    text: `¿Quieres añadir ${this.cantidad} ${this.cantidad > 1 ? 'unidades' : 'unidad'} de "${this.nombre}"${this.color ? ' (Color: ' + this.color + ')' : ''} a tu carrito?`,
                    icon: 'question',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: '✅ Sí, añadir',
                    cancelButtonText: '❌ Cancelar'
                }).then((result) => {
                    if (result.isConfirmed) {
                        const formData = new FormData();
                        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
                        formData.append('cantidad', this.cantidad);
                        formData.append('color', this.color);
                        
                        fetch('{% url "web:add_cart" producto.id %}', {
                            method: 'POST',
                            body: formData,
                            headers: {
                                'X-Requested-With': 'XMLHttpRequest',
                                'X-CSRFToken': '{{ csrf_token }}'
                            },
                            credentials: 'same-origin'
                        })
                        .then(response => {
                            if (!response.ok) throw new Error('Error HTTP: ' + response.status);
                            return response.json();
                        })
                        .then(data => {
                            if (data.success) {
                                if (data.cart_count !== undefined) {
                                    const span = document.querySelector('.h-cart-icon span');
                                    if (span) span.textContent = data.cart_count;
                                    actualizarMiniCarrito();
                                }
                                  Swal.fire({
                                    title: '¡Añadido con éxito!',
                                    text: data.message || `${this.cantidad} ${this.cantidad > 1 ? 'unidades' : 'unidad'} de "${this.nombre}" ${this.cantidad > 1 ? 'han sido añadidas' : 'ha sido añadida'} a tu carrito.`,
                                    icon: 'success',
                                    showCancelButton: true,
                                    confirmButtonText: '🛒 Ir al carrito',
                                    cancelButtonText: '🏠 Seguir comprando'
                                }).then((result) => {
                                    if (result.isConfirmed) {
                                        window.location.href = '{% url "web:carrito" %}';
                                    }
                                });
                            } else {
                                Swal.fire('Error', data.message || 'No se pudo añadir el producto.', 'error');
                            }
                        })
                        .catch(error => {
                            console.error(error);
                            Swal.fire('Error', 'Ha ocurrido un problema. Intenta nuevamente.', 'error');
                        });
                    }
                });
            }
        }
    }
    
    // Función para actualizar el mini-carrito (duplicada de catalogo.html)
    function actualizarMiniCarrito() {
        fetch('{% url "web:carrito" %}', {
            method: 'GET',
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            }
        })
        .then(response => response.text())
        .then(html => {
            const parser = new DOMParser();
            const doc = parser.parseFromString(html, 'text/html');

            const cartCount = doc.querySelector('.h-cart-icon span')?.textContent.trim();
            if (cartCount) {
                document.querySelector('.h-cart-icon span').textContent = cartCount;
            }

            const cartTotal = doc.querySelector('.h-cart-total')?.textContent.trim();
            if (cartTotal) {
                document.querySelector('.h-cart-total').textContent = cartTotal;
            }

            const cartList = doc.querySelector('.cart_list');
            if (cartList) {
                document.querySelector('.cart_list').innerHTML = cartList.innerHTML;
            }

            const totalElement = doc.querySelector('.widget_shopping_cart_content .total');
            if (totalElement) {
                document.querySelector('.widget_shopping_cart_content .total').innerHTML = totalElement.innerHTML;
            }
        })
        .catch(error => {
            console.error('Error al actualizar el mini-carrito:', error);
        });
    }
    </script>

</article>

{% endblock %}